# 从基础镜像安装依赖
FROM python:3.7.3 AS build
COPY ./conf/requirements.txt ./conf/run_step1.sh /tmp/
RUN /bin/bash /tmp/run_step1.sh

# 从alpine镜像运行程序
FROM python:3.7.3-alpine
COPY --from=build /install /usr/local
COPY . /app
WORKDIR /app

ENV DEBIAN_FRONTRND=nointeractive
